CREATE PROCEDURE [dbo].[load_hub_Biro40_Optik] as

TRUNCATE TABLE hub.Biro40_Optik

INSERT INTO hub.Biro40_Optik (Typ, [Lichtrichtung], [Einsatz], [Anfangswinkel], [Endwinkel], [Schnittmass_Max], [Schnitttyp], [optisches_System], [optisches_System_Kurztext])

SELECT * FROM (VALUES

('Einzeloptik', 'direkt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '90', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '90', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Mitteloptik', 'direkt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Ecke', 'direkt', 'primaer', '90', '90', '591', 'FIX', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '90', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '90', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '-45', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '45', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'primaer', '45', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Mitteloptik', 'direkt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Ecke', 'direkt', 'primaer', '90', '90', '591', 'FIX', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Mitteloptik', 'direkt indirekt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'primaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'primaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'primaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Ecke', 'direkt indirekt', 'primaer', '90', '90', '591', 'FIX', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '90', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '-45', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '-45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'primaer', '45', '45', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Mitteloptik', 'direkt indirekt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'primaer', '90', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'primaer', '45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'primaer', '-45', '90', '1500', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Ecke', 'direkt indirekt', 'primaer', '90', '90', '591', 'FIX', 'prismatisch (UGR <19)', 'PRI'),
	---
	---Indirekt
	---
	('Einzeloptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '90', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '90', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Mitteloptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Ecke', 'direkt', 'sekundaer', '90', '90', '591', 'FIX', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '90', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '90', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '-45', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt', 'sekundaer', '45', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Mitteloptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Ecke', 'direkt', 'sekundaer', '90', '90', '591', 'FIX', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '-45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '45', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Mitteloptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'satiniert', 'SAT'),
	('Ecke', 'direkt indirekt', 'sekundaer', '90', '90', '591', 'FIX', 'satiniert', 'SAT'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '90', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '-45', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '-45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Einzeloptik', 'direkt indirekt', 'sekundaer', '45', '45', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Anfangsoptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Mitteloptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '90', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Endoptik', 'direkt indirekt', 'sekundaer', '-45', '90', '3000', 'VAR', 'prismatisch (UGR <19)', 'PRI'),
	('Ecke', 'direkt indirekt', 'sekundaer', '90', '90', '591', 'FIX', 'prismatisch (UGR <19)', 'PRI')



)t ([Typ], [Lichtrichtung], [Einsatz], [Anfangswinkel], [Endwinkel], [Schnittmass_Max], [Schnitttyp], [optisches_System], [optisches_System_Kurztext])


