
CREATE PROCEDURE [dbo].[load_hub_Biro40_Profil] as

TRUNCATE TABLE hub.Biro40_Profil

INSERT INTO hub.Biro40_Profil ([Profiltyp], [Montageart], [Lichtrichtung], [Montageart_Kurztext], [Anfangswinkel], [Endwinkel], [Schnittmass_Max], [Schnitttyp], [Gehaeusefarbe], [Gehaeusefarbe_Kurztext]) 

SELECT * FROM (VALUES

	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Mittelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Ecke', 'Anbau', 'direkt', 'AN', '90', '90', '591', 'FIX', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Mittelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Ecke', 'Einbau', 'direkt', 'EI', '90', '90', '591', 'FIX', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Mittelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Ecke', 'Pendel direkt', 'direkt', 'PD', '90', '90', '591', 'FIX', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '-45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '45', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Mittelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'alu exloxiert', 'ALU'),
	('Ecke', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '591', 'FIX', 'alu exloxiert', 'ALU'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Mittelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Ecke', 'Anbau', 'direkt', 'AN', '90', '90', '591', 'FIX', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Mittelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Ecke', 'Einbau', 'direkt', 'EI', '90', '90', '591', 'FIX', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Mittelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Ecke', 'Pendel direkt', 'direkt', 'PD', '90', '90', '591', 'FIX', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '-45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '45', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Mittelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'schwarz eloxiert', 'SW'),
	('Ecke', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '591', 'FIX', 'schwarz eloxiert', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '90', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '-45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Anbau', 'direkt', 'AN', '45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Mittelprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Anbau', 'direkt', 'AN', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Ecke', 'Anbau', 'direkt', 'AN', '90', '90', '591', 'FIX', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '90', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '-45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Einbau', 'direkt', 'EI', '45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Mittelprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Einbau', 'direkt', 'EI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Ecke', 'Einbau', 'direkt', 'EI', '90', '90', '591', 'FIX', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt', 'direkt', 'PD', '45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Mittelprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt', 'direkt', 'PD', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Ecke', 'Pendel direkt', 'direkt', 'PD', '90', '90', '591', 'FIX', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '-45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Einzelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '45', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Anfangsprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Mittelprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Endprofil', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '-45', '90', '3000', 'VAR', 'weiss (RAL 9016)', 'W'),
	('Ecke', 'Pendel direkt indirekt', 'direkt indirekt', 'PI', '90', '90', '591', 'FIX', 'weiss (RAL 9016)', 'W')



)t ([Profiltyp], [Montageart], [Lichtrichtung], [Montageart_Kurztext], [Anfangswinkel], [Endwinkel], [Schnittmass_Max], [Schnitttyp], [Gehaeusefarbe], [Gehaeusefarbe_Kurztext])


