CREATE PROCEDURE [dbo].[load_hub_Melody_Stehleuchte] as

TRUNCATE TABLE hub.Melody_Stehleuchte

INSERT INTO hub.Melody_Stehleuchte (Hersteller, Leuchtenfamilie, Variante, Leuchtentyp, Gehaeusefarbe, Gehaeuseform, Montageart, Optik, Lichtrichtung, Lichtfarbe, Schaltungsart)
SELECT * FROM (VALUES


  ('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK und TASTER'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'WEISS', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SCHWARZ', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '1-KOPF STANDARD (7600 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF PARALLEL (15200 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF LINEAR (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '2-KOPF DIAGONAL RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF RECHTS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '3-KOPF LINKS (22800 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP'),
	('BRUMBERG', 'MELODY', 'MELODY STEHLEUCHTE', '4-KOPF STANDARD (30400 lm)', 'SILBER', 'KONSTRUKTION', 'BODEN', 'Nanoprismen (direkt) / Mikroprismen (indirekt)', 'Direkt / Indirekt', '4000 K', 'MIT SENSORIK, TASTER und APP')



)t (Hersteller, Leuchtenfamilie, Variante, Leuchtentyp, Gehaeusefarbe, Gehaeuseform, Montageart, Optik, Lichtrichtung, Lichtfarbe, Schaltungsart)


