
CREATE PROCEDURE [dbo].[load_hub_Biro40_Zubehoer] as

TRUNCATE TABLE hub.Biro40_Zubehoer

INSERT INTO hub.Biro40_Zubehoer ([Typ], [Montageart], [Lichtpunkthöhe], [Lichtrichtung], [Gehaeusefarbe], [Form])

SELECT * FROM (VALUES
('Enddeckel Anbau alu exloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Enddeckel Anbau schwarz eloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Anbau weiss (RAL 9016)', 'Anbau', 'direkter Anbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Einbau alu exloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Enddeckel Einbau schwarz eloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Einbau weiss (RAL 9016)', 'Einbau', 'direkter Einbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Enddeckel Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Enddeckel Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung Anbau alu exloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Einspeisung Anbau schwarz eloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung Anbau weiss (RAL 9016)', 'Anbau', 'direkter Anbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung Einbau alu exloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Einspeisung Einbau schwarz eloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung Einbau weiss (RAL 9016)', 'Einbau', 'direkter Einbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm alu exloxiert direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm schwarz eloxiert direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 1.500 mm weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm alu exloxiert direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm schwarz eloxiert direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 3.000 mm weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm alu exloxiert direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm schwarz eloxiert direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Einspeisung inkl. Deckenbaldachin, L = 5.000 mm weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Anbau alu exloxiert direkt', 'Anbau', 'direkter Anbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Befestigung Anbau schwarz eloxiert direkt', 'Anbau', 'direkter Anbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Anbau weiss (RAL 9016) direkt', 'Anbau', 'direkter Anbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Einbau alu exloxiert direkt', 'Einbau', 'direkter Einbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Befestigung Einbau schwarz eloxiert direkt', 'Einbau', 'direkter Einbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Einbau weiss (RAL 9016) direkt', 'Einbau', 'direkter Einbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt alu exloxiert direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt schwarz eloxiert direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt indirekt alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt alu exloxiert direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt schwarz eloxiert direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt indirekt alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt alu exloxiert direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt schwarz eloxiert direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt weiss (RAL 9016) direkt', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Befestigung Pendel direkt indirekt alu exloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt schwarz eloxiert direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Befestigung Pendel direkt indirekt weiss (RAL 9016) direkt indirekt', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Anbau alu exloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Anbau schwarz eloxiert', 'Anbau', 'direkter Anbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Anbau weiss (RAL 9016)', 'Anbau', 'direkter Anbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Einbau alu exloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Einbau schwarz eloxiert', 'Einbau', 'direkter Einbau', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Einbau weiss (RAL 9016)', 'Einbau', 'direkter Einbau', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 1,5m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 1,5m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 3,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 3,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt alu exloxiert', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt schwarz eloxiert', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt weiss (RAL 9016)', 'Pendel direkt', 'LPH 5,0m', 'direkt', 'weiss (RAL 9016)', 'Standard'),
	('Linienverbinder Pendel direkt indirekt alu exloxiert', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'alu exloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt schwarz eloxiert', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'schwarz eloxiert', 'Standard'),
	('Linienverbinder Pendel direkt indirekt weiss (RAL 9016)', 'Pendel direkt indirekt', 'LPH 5,0m', 'direkt indirekt', 'weiss (RAL 9016)', 'Standard')


)t ([Typ], [Montageart], [Lichtpunkthöhe], [Lichtrichtung], [Gehaeusefarbe], [Form])