--CREATE PROCEDURE [dbo].[load_all] as
--
----
------ HUBS
--TRUNCATE TABLE hub.Leuchten;
--TRUNCATE TABLE hub.Steuerung;
--TRUNCATE TABLE hub.Treiber;
--TRUNCATE TABLE hub.LED;
----TRUNCATE TABLE hub.Lichtverteilung_Klasse;
----TRUNCATE TABLE hub.Lichtstrom_Klasse;
----TRUNCATE TABLE hub.Lichtfarbe_Klasse;
----TRUNCATE TABLE hub.Schaltungsart_Klasse;a
----
----
--exec load_hub_Leuchten;
--exec load_hub_Steuerung;
--exec load_hub_Treiber;
--exec load_hub_LED;
----exec load_hub_Optik_Klasse;
----exec load_hub_Lichtverteilung_Klasse;
----exec load_hub_Lichtstrom_Klasse;
----exec load_hub_Lichtfarbe_Klasse;
----exec load_hub_Schaltungsart_Klasse
----
----
----
----
------LINKS
----
----
--TRUNCATE TABLE link.Leuchten__Steuerung;
--TRUNCATE TABLE link.Leuchten__LED;
--TRUNCATE TABLE link.Steuerung__Treiber;
----TRUNCATE TABLE link.Lichtverteilung_Klasse__Produkt_Typ_Klasse__Leuchten_Laenge_Klasse__Optik_Klasse__Lichtstrom_Klasse;
----TRUNCATE TABLE link.Lichtstrom_Klasse__Produkt_Typ_Klasse__Leuchten_Laenge_Klasse__Optik_Klasse__Lichtfarbe_Klasse;
----TRUNCATE TABLE link.Lichtfarbe_Klasse__Schaltungsart_Klasse;
----
--exec load_link_Leuchten__Steuerung;
--exec load_link_Leuchten__LED;
--exec load_link_Steuerung__Treiber;
----exec load_link_Leuchten_Laenge_Klasse__Optik_Klasse;
----exec load_link_Produkt_Typ_Klasse__Leuchten_Laenge_Klasse__Optik_Klasse__Lichtverteilung_Klasse;
----exec load_link_Lichtverteilung_Klasse__Produkt_Typ_Klasse__Leuchten_Laenge_Klasse__Optik_Klasse__Lichtstrom_Klasse;
----exec load_link_Lichtstrom_Klasse__Produkt_Typ_Klasse__Leuchten_Laenge_Klasse__Optik_Klasse__Lichtfarbe_Klasse;
----exec load_link_Lichtfarbe_Klasse__Schaltungsart_Klasse;
--
-----SATS
--
--TRUNCATE TABLE sat.Steuerung_MA;
--TRUNCATE TABLE sat.Treiber_MA;
--
--exec load_sat_Steuerung_MA;
--exec load_sat_Treiber_MA;
--
--
--
--
--


