
CREATE PROCEDURE [dbo].[load_hub_M1_Gehaeuse] as

TRUNCATE TABLE hub.M1_Gehaeuse

INSERT INTO hub.M1_Gehaeuse ( 
       [Leuchtentyp]
      ,[Typ_DE]
      ,[Typ_EN]
      ,[Farbe_DE]
      ,[Farbe_EN]
      ,[Form_DE]
      ,[Form_EN]
      ,[Montageart_DE]
      ,[Montageart_EN]
      ,[Montageart_2_DE]
      ,[Montageart_2_EN]
      ,[Montageart_3_DE]
      ,[Montageart_3_EN]
      ,[Verstellbarkeit_DE]
      ,[Verstellbarkeit_EN]
	  )

SELECT * FROM (VALUES

  ('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Einbaugehäuse', 'Recessed housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Einbaumontage', 'Recessed mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'vertieft', 'recessed', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'rund', 'Round', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterung vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß / strukturschwarz', 'white structure / black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz / strukturweiß', 'black structure / white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß / strukturschwarz', 'white structure / black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz / strukturweiß', 'black structure / white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß / strukturschwarz', 'white structure / black structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz / strukturweiß', 'black structure / white structure', 'sonstige', 'Other', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen bündig', 'with module holder flush', 'starr', 'fixed'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturweiß', 'white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'strukturschwarz', 'black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturweiß / innen strukturschwarz', 'outside white structure / inside black structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', 'with module holder recessed', 'schwenkbar', 'swivelling'),
	('M1', 'Anbaugehäuse', 'Surface mounted housing', 'außen strukturschwarz / innen strukturweiß', 'outside black structure / inside white structure', 'quadratisch', 'Square', 'Anbaumontage', 'Surface mounting', 'bündig', 'flush', 'mit Modulhalterungen vertieft', '', 'schwenkbar', 'swivelling')


)t (   [Leuchtentyp]
      ,[Typ_DE]
      ,[Typ_EN]
      ,[Farbe_DE]
      ,[Farbe_EN]
      ,[Form_DE]
      ,[Form_EN]
      ,[Montageart_DE]
      ,[Montageart_EN]
      ,[Montageart_2_DE]
      ,[Montageart_2_EN]
      ,[Montageart_3_DE]
      ,[Montageart_3_EN]
      ,[Verstellbarkeit_DE]
      ,[Verstellbarkeit_EN]
	 )


