CREATE PROCEDURE [dbo].[load_hub_Spot_Gehaeuse] as

TRUNCATE TABLE hub.Spot_Gehaeuse

INSERT INTO hub.Spot_Gehaeuse ([Leuchtentyp], [Typ], [Farbe_DE], [Farbe_EN], [Form_DE], [Form_EN]) 

SELECT * FROM (VALUES

  ('MR16', '63', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '63', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '63', 'strukturweiß', 'white structure', 'rund', 'Round'),
	('MR16', '63', 'schwarz', 'black', 'rund', 'Round'),
	('MR16', '63', 'alu matt', 'alu matt', 'rund', 'Round'),
	('MR16', '63', 'champagner matt', 'champagne matt', 'rund', 'Round'),
	('MR16', '63', 'titan matt', 'titanium matt', 'rund', 'Round'),
	('MR16', '63', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '63', 'schwarz', 'black', 'rund', 'Round'),
	('MR16', '63', 'alu matt', 'alu matt', 'rund', 'Round'),
	('MR16', '64', 'schwarz / alu matt', 'black / alu matt', 'rund', 'Round'),
	('MR16', '65', 'chrom', 'chrome', 'quadratisch', 'Square'),
	('MR16', '65', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '65', 'strukturweiß', 'white structure', 'quadratisch', 'Square'),
	('MR16', '65', 'schwarz', 'black', 'quadratisch', 'Square'),
	('MR16', '65', 'alu matt', 'alu matt', 'quadratisch', 'Square'),
	('MR16', '65', 'champagner matt', 'champagne matt', 'quadratisch', 'Square'),
	('MR16', '65', 'titan matt', 'titanium matt', 'quadratisch', 'Square'),
	('MR16', '66', 'schwarz / alu matt', 'black / alu matt', 'quadratisch', 'Square'),
	('MR16', '1963', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '1963', 'chrom matt', 'chrome satin', 'rund', 'Round'),
	('MR16', '1963', 'gold', 'gold', 'rund', 'Round'),
	('MR16', '1963', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '1963', 'strukturweiß', 'white structure', 'rund', 'Round'),
	('MR16', '1963', 'schwarz', 'black', 'rund', 'Round'),
	('MR16', '1963', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '1964', 'chrom', 'chrome', 'quadratisch', 'Square'),
	('MR16', '1964', 'chrom matt', 'chrome satin', 'quadratisch', 'Square'),
	('MR16', '1964', 'gold', 'gold', 'quadratisch', 'Square'),
	('MR16', '1964', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '1964', 'strukturweiß', 'white structure', 'quadratisch', 'Square'),
	('MR16', '1964', 'schwarz', 'black', 'quadratisch', 'Square'),
	('MR16', '1964', 'nickel matt', 'nickel satin', 'quadratisch', 'Square'),
	('MR16', '2110', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '2110', 'gold', 'gold', 'rund', 'Round'),
	('MR16', '2110', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2110', 'edelchrom', 'noble chrome', 'rund', 'Round'),
	('MR16', '2110', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '2111', 'chrom', 'chrome', 'quadratisch', 'Square'),
	('MR16', '2111', 'gold', 'gold', 'quadratisch', 'Square'),
	('MR16', '2111', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '2111', 'edelchrom', 'noble chrome', 'quadratisch', 'Square'),
	('MR16', '2111', 'nickel matt', 'nickel satin', 'quadratisch', 'Square'),
	('MR16', '2034', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '2034', 'chrom matt', 'chrome satin', 'rund', 'Round'),
	('MR16', '2034', 'gold', 'gold', 'rund', 'Round'),
	('MR16', '2034', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2034', 'schwarz', 'black', 'rund', 'Round'),
	('MR16', '2034', 'bronze', 'bronze', 'rund', 'Round'),
	('MR16', '282', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '283', 'chrom', 'chrome', 'quadratisch', 'Square'),
	('MR16', '37005', 'strukturweiß', 'white structure', 'rund', 'Round'),
	('MR16', '37005', 'strukturschwarz', 'black structure', 'rund', 'Round'),
	('MR16', '37005', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '37006', 'strukturweiß', 'white structure', 'quadratisch', 'Square'),
	('MR16', '37006', 'strukturschwarz', 'black structure', 'quadratisch', 'Square'),
	('MR16', '37006', 'edelstahl', 'stainless steel', 'quadratisch', 'Square'),
	('MR16', '37015', 'strukturweiß', 'white structure', 'rund', 'Round'),
	('MR16', '37015', 'strukturschwarz', 'black structure', 'rund', 'Round'),
	('MR16', '37015', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '37016', 'strukturweiß', 'white structure', 'quadratisch', 'Square'),
	('MR16', '37016', 'strukturschwarz', 'black structure', 'quadratisch', 'Square'),
	('MR16', '37016', 'edelstahl', 'stainless steel', 'quadratisch', 'Square'),
	('MR16', '2169', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '2169', 'chrom matt', 'chrome satin', 'rund', 'Round'),
	('MR16', '2169', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2169', 'gold', 'gold', 'rund', 'Round'),
	('MR16', '2295', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '2295', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2295', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '2295', 'messing', 'brass', 'rund', 'Round'),
	('MR16', '2296', 'chrom', 'chrome', 'quadratisch', 'Square'),
	('MR16', '2296', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '2296', 'nickel matt', 'nickel satin', 'quadratisch', 'Square'),
	('MR16', '2296', 'messing', 'brass', 'quadratisch', 'Square'),
	('MR16', '2062', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '2062', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2062', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '2339', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '1180', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '1181', 'edelstahl', 'stainless steel', 'quadratisch', 'Square'),
	('MR16', '2191', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '2191', 'edelstahl klar gepulvert', 'stainless steel clear powdered', 'rund', 'Round'),
	('MR16', '2191', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '69', 'alu matt', 'alu matt', 'rund', 'Round'),
	('MR16', '70', 'alu matt', 'alu matt', 'quadratisch', 'Square'),
	('MR16', '51281', 'alu matt', 'alu matt', 'quadratisch', 'Square'),
	('MR16', '20353', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '20353', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '20353', 'silber', 'silver', 'rund', 'Round'),
	('MR16', '20355', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '20355', 'nickel matt', 'nickel satin', 'quadratisch', 'Square'),
	('MR16', '20355', 'silber', 'silver', 'quadratisch', 'Square'),
	('MR16', '20001', 'strukturweiß', 'white structure', 'quadratisch', 'Square'),
	('MR16', '20001', 'alu matt', 'alu matt', 'quadratisch', 'Square'),
	('MR16', '45320', 'weiß mit Dekoglas klar', 'white with clear decorative glass', 'rund', 'Round'),
	('MR16', '45320', 'schwarz mit Dekoglas klar', 'black with clear decorative glass', 'rund', 'Round'),
	('MR16', '45321', 'weiß mit Dekoglas klar', 'white with clear decorative glass', 'quadratisch', 'Square'),
	('MR16', '45321', 'schwarz mit Dekoglas klar', 'black with clear decorative glass', 'quadratisch', 'Square'),
	('MR16', '20368', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '20368', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '20368', 'silber', 'silver', 'rund', 'Round'),
	('MR16', '26004', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '26004', 'schwarz', 'black', 'rund', 'Round'),
	('MR16', '26004', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '26005', 'weiß', 'white', 'quadratisch', 'Square'),
	('MR16', '26005', 'schwarz', 'black', 'quadratisch', 'Square'),
	('MR16', '26005', 'edelstahl', 'stainless steel', 'quadratisch', 'Square'),
	('MR16', '1996', 'chrom', 'chrome', 'rund', 'Round'),
	('MR16', '1996', 'weiß', 'white', 'rund', 'Round'),
	('MR16', '1996', 'nickel matt', 'nickel satin', 'rund', 'Round'),
	('MR16', '1996', 'gold', 'gold', 'rund', 'Round'),
	('MR16', '1996', 'edelstahl klar gepulvert', 'stainless steel clear powdered', 'rund', 'Round'),
	('MR16', '1996', 'edelstahl', 'stainless steel', 'rund', 'Round'),
	('MR16', '1996', 'gold / weiß / gold', 'gold / white / gold', 'rund', 'Round')





)t ([Leuchtentyp], [Typ], [Farbe_DE], [Farbe_EN], [Form_DE], [Form_EN])


